spring.application.name=fare-service
server.port=8084

# MongoDB Persistence Boundary
spring.data.mongodb.uri=mongodb://localhost:27017/ridelink_payment_db

# Shared JWT Secret
jwt.secret=RideLinkSecretKeyForJwtSigning2026SecureKeyWith256BitsMin!

# Interservice Communication URLs
services.ride-service.url=http://localhost:8083

# SpringDoc OpenAPI Documentation
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
