spring.application.name=driver-service
server.port=8082

# MongoDB Persistence Boundary for Driver & Vehicle Service
spring.data.mongodb.uri=mongodb://localhost:27017/ridelink_driver_db
spring.data.mongodb.auto-index-creation=true

# Interservice Communication - Account Service Endpoint
services.account-service.url=http://localhost:8081

# JWT Configuration (Shared signature secret for microservices cluster)
jwt.secret=mySuperSecretKeyForRideLinkJWTAuthentication2026VerySecureKeyRideLink2026
jwt.expiration=86400000

# SpringDoc OpenAPI Documentation
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
