spring.application.name=account-service
server.port=8081

# MongoDB Configuration (Dedicated persistence boundary for Account Service)
spring.data.mongodb.uri=mongodb://localhost:27017/ridelink_account_db
spring.data.mongodb.auto-index-creation=true

# JWT Configuration
jwt.secret=mySuperSecretKeyForRideLinkJWTAuthentication2026VerySecureKeyRideLink2026
jwt.expiration=86400000

# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method