spring.application.name=ride-service
server.port=8083

# MongoDB Persistence Boundary
spring.data.mongodb.uri=mongodb://localhost:27017/ridelink_ride_db

# Shared JWT Secret
jwt.secret=RideLinkSecretKeyForJwtSigning2026SecureKeyWith256BitsMin!

# Interservice Communication URLs
services.account-service.url=http://localhost:8081
services.driver-service.url=http://localhost:8082

# SpringDoc OpenAPI Documentation
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
